// AEGIS SafeVault™ Mock Data

import {
  EmergencySavings,
  PreparednessScore,
  ClimateRiskAnalysis,
  EmergencyReserve,
  Drone,
  DroneDelivery,
  ElderlyProfile,
  SOSAlert,
  AIInsight,
  SafeVaultAnalytics,
  SurvivalKit,
  InactivityAlert,
} from '@/types/safevault';

// Emergency Savings Mock Data
export const mockEmergencySavings: EmergencySavings = {
  id: 'sav-001',
  userId: 'user-001',
  balance: 12500.00,
  monthlyContribution: 500.00,
  savingsPercentage: 15,
  targetAmount: 25000.00,
  currency: 'USD',
  autoSave: true,
  createdAt: new Date('2024-01-15'),
  lastContribution: new Date('2024-05-01'),
  totalSaved: 12500.00,
  withdrawals: [
    {
      id: 'txn-w-001',
      type: 'emergency-use',
      amount: 1500.00,
      date: new Date('2024-03-20'),
      description: 'Emergency medical supplies during flood',
      emergencyId: 'emg-flood-001',
    },
  ],
  contributions: [
    {
      id: 'txn-c-001',
      type: 'contribution',
      amount: 500.00,
      date: new Date('2024-05-01'),
      description: 'Monthly auto-save',
    },
    {
      id: 'txn-c-002',
      type: 'contribution',
      amount: 500.00,
      date: new Date('2024-04-01'),
      description: 'Monthly auto-save',
    },
  ],
};

// Preparedness Score Mock Data
export const mockPreparednessScore: PreparednessScore = {
  overall: 78,
  financial: 85,
  supplies: 72,
  knowledge: 80,
  communication: 75,
  level: 'good',
  recommendations: [
    'Increase water supply to 3-day minimum',
    'Add first aid training certification',
    'Update emergency contact list',
    'Test communication devices monthly',
  ],
  lastCalculated: new Date(),
};

// Climate Risk Analysis Mock Data
export const mockClimateRisks: ClimateRiskAnalysis[] = [
  {
    id: 'risk-001',
    location: {
      address: 'San Francisco Bay Area, CA',
      coordinates: { lat: 37.7749, lng: -122.4194 },
      region: 'Northern California',
      country: 'USA',
    },
    risks: [
      {
        id: 'risk-earthquake-001',
        type: 'earthquake',
        severity: 'high',
        probability: 72,
        timeframe: 'Next 30 years',
        affectedPopulation: 7500000,
        description: 'Major earthquake risk along San Andreas Fault',
        mitigationSteps: [
          'Secure heavy furniture and appliances',
          'Create earthquake emergency kit',
          'Identify safe spots in each room',
          'Practice drop, cover, and hold on',
        ],
        historicalData: {
          lastOccurrence: new Date('1989-10-17'),
          frequency: 1,
          averageDamage: '$6 billion',
        },
      },
      {
        id: 'risk-wildfire-001',
        type: 'wildfire',
        severity: 'moderate',
        probability: 45,
        timeframe: 'Summer 2024',
        affectedPopulation: 250000,
        description: 'Elevated wildfire risk during dry season',
        mitigationSteps: [
          'Create defensible space around property',
          'Prepare evacuation plan',
          'Monitor air quality alerts',
          'Keep N95 masks ready',
        ],
      },
    ],
    overallThreatLevel: 'high',
    predictions: [
      {
        id: 'pred-001',
        type: 'earthquake',
        predictedDate: new Date('2024-08-15'),
        confidence: 35,
        severity: 'high',
        affectedAreas: ['San Francisco', 'Oakland', 'San Jose'],
        estimatedImpact: {
          casualties: '500-2000',
          economicDamage: '$50-100 billion',
          displacedPeople: 500000,
        },
        preparednessActions: [
          'Stock 2-week emergency supplies',
          'Secure water heater and gas lines',
          'Identify evacuation routes',
          'Establish family communication plan',
        ],
        evacuationRecommended: false,
      },
    ],
    recommendations: [
      'Increase emergency fund to 6 months expenses',
      'Purchase earthquake insurance',
      'Conduct quarterly emergency drills',
      'Install seismic gas shutoff valve',
    ],
    lastUpdated: new Date(),
    dataSource: 'USGS, NOAA, Local Emergency Services',
  },
  {
    id: 'risk-002',
    location: {
      address: 'Miami-Dade County, FL',
      coordinates: { lat: 25.7617, lng: -80.1918 },
      region: 'South Florida',
      country: 'USA',
    },
    risks: [
      {
        id: 'risk-hurricane-001',
        type: 'hurricane',
        severity: 'critical',
        probability: 85,
        timeframe: 'Hurricane Season 2024',
        affectedPopulation: 2700000,
        description: 'High probability of major hurricane landfall',
        mitigationSteps: [
          'Install hurricane shutters',
          'Prepare evacuation kit',
          'Secure outdoor items',
          'Review insurance coverage',
        ],
        historicalData: {
          lastOccurrence: new Date('2017-09-10'),
          frequency: 3,
          averageDamage: '$25 billion',
        },
      },
      {
        id: 'risk-flood-001',
        type: 'flood',
        severity: 'high',
        probability: 68,
        timeframe: 'Next 12 months',
        affectedPopulation: 450000,
        description: 'Coastal flooding and storm surge risk',
        mitigationSteps: [
          'Elevate critical utilities',
          'Purchase flood insurance',
          'Create flood barrier plan',
          'Identify high ground evacuation routes',
        ],
      },
    ],
    overallThreatLevel: 'critical',
    predictions: [
      {
        id: 'pred-002',
        type: 'hurricane',
        predictedDate: new Date('2024-09-15'),
        confidence: 65,
        severity: 'critical',
        affectedAreas: ['Miami', 'Fort Lauderdale', 'West Palm Beach'],
        estimatedImpact: {
          casualties: '100-500',
          economicDamage: '$30-80 billion',
          displacedPeople: 1200000,
        },
        preparednessActions: [
          'Stock 2-week supplies including water',
          'Prepare home for 150mph winds',
          'Identify evacuation zone',
          'Arrange pet-friendly shelter',
        ],
        evacuationRecommended: true,
      },
    ],
    recommendations: [
      'Mandatory evacuation plan preparation',
      'Increase emergency savings to $10,000',
      'Install backup generator',
      'Create digital copies of important documents',
    ],
    lastUpdated: new Date(),
    dataSource: 'NOAA, National Hurricane Center',
  },
];

// Emergency Reserve Mock Data
export const mockEmergencyReserve: EmergencyReserve = {
  id: 'reserve-001',
  userId: 'user-001',
  householdSize: 4,
  items: [
    {
      id: 'item-001',
      name: 'Bottled Water (1 gallon)',
      category: 'water',
      quantity: 24,
      unit: 'gallons',
      expiryDate: new Date('2025-12-31'),
      location: 'Garage Storage',
      priority: 'essential',
      status: 'adequate',
      recommendedQuantity: 48,
      cost: 48.00,
      supplier: 'Costco',
      lastChecked: new Date('2024-05-01'),
    },
    {
      id: 'item-002',
      name: 'Canned Food (Mixed)',
      category: 'food',
      quantity: 36,
      unit: 'cans',
      expiryDate: new Date('2026-03-15'),
      location: 'Pantry',
      priority: 'essential',
      status: 'adequate',
      recommendedQuantity: 48,
      cost: 72.00,
      lastChecked: new Date('2024-05-01'),
    },
    {
      id: 'item-003',
      name: 'First Aid Kit (Comprehensive)',
      category: 'medical',
      quantity: 2,
      unit: 'kits',
      location: 'Bathroom Cabinet',
      priority: 'essential',
      status: 'adequate',
      recommendedQuantity: 2,
      cost: 89.99,
      lastChecked: new Date('2024-04-15'),
    },
    {
      id: 'item-004',
      name: 'Flashlight with Batteries',
      category: 'power',
      quantity: 3,
      unit: 'units',
      location: 'Emergency Kit',
      priority: 'essential',
      status: 'adequate',
      recommendedQuantity: 4,
      cost: 45.00,
      lastChecked: new Date('2024-05-01'),
    },
    {
      id: 'item-005',
      name: 'Battery-Powered Radio',
      category: 'communication',
      quantity: 1,
      unit: 'unit',
      location: 'Emergency Kit',
      priority: 'important',
      status: 'adequate',
      recommendedQuantity: 1,
      cost: 35.00,
      lastChecked: new Date('2024-05-01'),
    },
    {
      id: 'item-006',
      name: 'Baby Formula',
      category: 'baby',
      quantity: 4,
      unit: 'cans',
      expiryDate: new Date('2024-08-30'),
      location: 'Kitchen Cabinet',
      priority: 'essential',
      status: 'low',
      recommendedQuantity: 12,
      cost: 120.00,
      lastChecked: new Date('2024-05-01'),
    },
    {
      id: 'item-007',
      name: 'Portable Power Bank (20000mAh)',
      category: 'power',
      quantity: 2,
      unit: 'units',
      location: 'Bedroom',
      priority: 'important',
      status: 'adequate',
      recommendedQuantity: 2,
      cost: 79.98,
      lastChecked: new Date('2024-05-01'),
    },
    {
      id: 'item-008',
      name: 'Emergency Blankets',
      category: 'shelter',
      quantity: 6,
      unit: 'blankets',
      location: 'Emergency Kit',
      priority: 'important',
      status: 'adequate',
      recommendedQuantity: 8,
      cost: 24.00,
      lastChecked: new Date('2024-05-01'),
    },
  ],
  totalValue: 513.97,
  lastUpdated: new Date(),
  adequacyScore: 72,
  recommendations: [
    'Increase water supply to 48 gallons (3-day supply)',
    'Restock baby formula before expiry',
    'Add one more flashlight',
    'Consider adding water purification tablets',
  ],
};

// Survival Kits Mock Data
export const mockSurvivalKits: SurvivalKit[] = [
  {
    id: 'kit-001',
    name: 'Basic 72-Hour Kit',
    type: 'basic',
    items: mockEmergencyReserve.items.slice(0, 5),
    totalCost: 289.99,
    duration: 3,
    peopleSupported: 1,
    completeness: 85,
  },
  {
    id: 'kit-002',
    name: 'Family Emergency Kit',
    type: 'family',
    items: mockEmergencyReserve.items,
    totalCost: 513.97,
    duration: 7,
    peopleSupported: 4,
    completeness: 72,
  },
];

// Drone Fleet Mock Data
export const mockDrones: Drone[] = [
  {
    id: 'drone-001',
    name: 'AEGIS Air Alpha-1',
    model: 'AA-X1000',
    status: 'idle',
    location: { lat: 37.7749, lng: -122.4194, altitude: 0 },
    battery: 95,
    maxPayload: 25,
    currentPayload: 0,
    range: 50,
    speed: 80,
    maintenanceSchedule: new Date('2024-06-15'),
    flightHours: 247,
    lastMaintenance: new Date('2024-04-15'),
  },
  {
    id: 'drone-002',
    name: 'AEGIS Air Beta-2',
    model: 'AA-X1000',
    status: 'in-transit',
    location: { lat: 37.7849, lng: -122.4094, altitude: 150 },
    battery: 67,
    maxPayload: 25,
    currentPayload: 15,
    range: 50,
    speed: 75,
    assignedDelivery: {
      id: 'delivery-001',
      droneId: 'drone-002',
      emergencyId: 'emg-001',
      status: 'in-transit',
      priority: 'critical',
      origin: {
        lat: 37.7749,
        lng: -122.4194,
        address: 'AEGIS Distribution Center, San Francisco',
      },
      destination: {
        lat: 37.8044,
        lng: -122.2712,
        address: '123 Emergency Lane, Oakland, CA',
      },
      route: [
        { lat: 37.7749, lng: -122.4194, altitude: 150, timestamp: new Date(), speed: 80 },
        { lat: 37.7849, lng: -122.4094, altitude: 150, timestamp: new Date(), speed: 75 },
      ],
      items: [
        { id: 'di-001', name: 'Medical Kit', category: 'medical', quantity: 2, weight: 5, urgent: true },
        { id: 'di-002', name: 'Water (5L)', category: 'water', quantity: 2, weight: 10, urgent: true },
      ],
      totalWeight: 15,
      estimatedArrival: new Date(Date.now() + 15 * 60000),
      dispatchTime: new Date(Date.now() - 10 * 60000),
      distance: 12.5,
      recipient: {
        name: 'John Martinez',
        phone: '+1-555-0123',
        instructions: 'Leave at front porch, ring doorbell',
      },
    },
    maintenanceSchedule: new Date('2024-06-20'),
    flightHours: 189,
    lastMaintenance: new Date('2024-04-20'),
  },
  {
    id: 'drone-003',
    name: 'AEGIS Air Gamma-3',
    model: 'AA-X2000',
    status: 'dispatched',
    location: { lat: 37.7649, lng: -122.4294, altitude: 200 },
    battery: 88,
    maxPayload: 35,
    currentPayload: 20,
    range: 75,
    speed: 90,
    maintenanceSchedule: new Date('2024-07-01'),
    flightHours: 156,
    lastMaintenance: new Date('2024-05-01'),
  },
  {
    id: 'drone-004',
    name: 'AEGIS Air Delta-4',
    model: 'AA-X1000',
    status: 'maintenance',
    location: { lat: 37.7749, lng: -122.4194, altitude: 0 },
    battery: 100,
    maxPayload: 25,
    currentPayload: 0,
    range: 50,
    speed: 80,
    maintenanceSchedule: new Date('2024-05-20'),
    flightHours: 312,
    lastMaintenance: new Date('2024-05-15'),
  },
];

// Elderly Profiles Mock Data
export const mockElderlyProfiles: ElderlyProfile[] = [
  {
    id: 'elderly-001',
    name: 'Margaret Thompson',
    age: 78,
    avatar: 'https://i.pravatar.cc/150?img=47',
    phone: '+1-555-0145',
    address: '456 Oak Street, San Francisco, CA 94102',
    coordinates: { lat: 37.7799, lng: -122.4184 },
    medicalConditions: ['Hypertension', 'Type 2 Diabetes', 'Arthritis'],
    medications: ['Lisinopril 10mg', 'Metformin 500mg', 'Ibuprofen 200mg'],
    allergies: ['Penicillin', 'Shellfish'],
    mobility: 'assisted',
    cognitiveStatus: 'mild-impairment',
    caregivers: [
      {
        id: 'cg-001',
        name: 'Sarah Thompson',
        relationship: 'Daughter',
        phone: '+1-555-0146',
        email: 'sarah.thompson@email.com',
        isPrimary: true,
        availability: 'Mon-Fri 9AM-5PM',
        notificationPreferences: { sms: true, email: true, push: true },
      },
      {
        id: 'cg-002',
        name: 'Home Care Services',
        relationship: 'Professional Caregiver',
        phone: '+1-555-0147',
        isPrimary: false,
        availability: 'Daily 8AM-8PM',
        notificationPreferences: { sms: true, email: false, push: true },
      },
    ],
    emergencyContacts: [
      {
        id: 'ec-001',
        name: 'Sarah Thompson',
        relationship: 'Daughter',
        phone: '+1-555-0146',
        email: 'sarah.thompson@email.com',
        isPrimary: true,
      },
      {
        id: 'ec-002',
        name: 'Dr. Robert Chen',
        relationship: 'Primary Physician',
        phone: '+1-555-0148',
        email: 'dr.chen@hospital.com',
        isPrimary: false,
      },
    ],
    devices: [
      {
        id: 'dev-001',
        type: 'wearable',
        name: 'Smart Health Watch',
        status: 'active',
        battery: 78,
        lastSignal: new Date(),
      },
      {
        id: 'dev-002',
        type: 'fall-detector',
        name: 'Fall Detection Pendant',
        status: 'active',
        battery: 92,
        lastSignal: new Date(),
        location: 'Worn',
      },
      {
        id: 'dev-003',
        type: 'panic-button',
        name: 'Emergency Button',
        status: 'active',
        lastSignal: new Date(),
        location: 'Bedroom',
      },
    ],
    lastCheckIn: new Date(Date.now() - 2 * 3600000),
    riskLevel: 'medium',
  },
  {
    id: 'elderly-002',
    name: 'Robert Williams',
    age: 82,
    avatar: 'https://i.pravatar.cc/150?img=33',
    phone: '+1-555-0149',
    address: '789 Pine Avenue, Oakland, CA 94601',
    coordinates: { lat: 37.8044, lng: -122.2712 },
    medicalConditions: ['Heart Disease', 'COPD', 'Dementia'],
    medications: ['Atorvastatin 20mg', 'Albuterol Inhaler', 'Donepezil 10mg'],
    allergies: ['Aspirin'],
    mobility: 'wheelchair',
    cognitiveStatus: 'moderate-impairment',
    caregivers: [
      {
        id: 'cg-003',
        name: 'Michael Williams',
        relationship: 'Son',
        phone: '+1-555-0150',
        email: 'michael.w@email.com',
        isPrimary: true,
        availability: '24/7',
        notificationPreferences: { sms: true, email: true, push: true },
      },
    ],
    emergencyContacts: [
      {
        id: 'ec-003',
        name: 'Michael Williams',
        relationship: 'Son',
        phone: '+1-555-0150',
        email: 'michael.w@email.com',
        isPrimary: true,
      },
    ],
    devices: [
      {
        id: 'dev-004',
        type: 'motion-sensor',
        name: 'Room Motion Detector',
        status: 'active',
        lastSignal: new Date(),
        location: 'Living Room',
      },
      {
        id: 'dev-005',
        type: 'door-sensor',
        name: 'Front Door Sensor',
        status: 'active',
        lastSignal: new Date(),
        location: 'Front Door',
      },
    ],
    lastCheckIn: new Date(Date.now() - 30 * 60000),
    riskLevel: 'high',
  },
];

// SOS Alerts Mock Data
export const mockSOSAlerts: SOSAlert[] = [
  {
    id: 'sos-001',
    elderlyId: 'elderly-001',
    type: 'fall-detected',
    severity: 'critical',
    timestamp: new Date(Date.now() - 15 * 60000),
    location: {
      lat: 37.7799,
      lng: -122.4184,
      address: '456 Oak Street, San Francisco, CA 94102',
    },
    description: 'Fall detected in bathroom. No response to automated check-in.',
    vitals: {
      heartRate: 95,
      bloodPressure: '145/92',
      oxygenLevel: 94,
    },
    status: 'responding',
    respondingTeams: ['team-medical-001'],
    notifiedContacts: ['cg-001', 'ec-001'],
    responseTime: 8,
  },
  {
    id: 'sos-002',
    elderlyId: 'elderly-002',
    type: 'manual-sos',
    severity: 'life-threatening',
    timestamp: new Date(Date.now() - 5 * 60000),
    location: {
      lat: 37.8044,
      lng: -122.2712,
      address: '789 Pine Avenue, Oakland, CA 94601',
    },
    description: 'Emergency button pressed. Difficulty breathing reported.',
    vitals: {
      heartRate: 115,
      bloodPressure: '160/100',
      oxygenLevel: 88,
      temperature: 99.2,
    },
    status: 'active',
    respondingTeams: ['team-medical-002', 'team-ambulance-001'],
    notifiedContacts: ['cg-003', 'ec-003'],
  },
];

// Inactivity Alerts Mock Data
export const mockInactivityAlerts: InactivityAlert[] = [
  {
    id: 'inact-001',
    elderlyId: 'elderly-001',
    detectedAt: new Date(Date.now() - 6 * 3600000),
    duration: 6,
    lastActivity: new Date(Date.now() - 6 * 3600000),
    activityType: 'Motion detected',
    location: 'Bedroom',
    aiAnalysis: {
      riskLevel: 'medium',
      possibleCauses: [
        'Extended sleep period',
        'Possible illness',
        'Device malfunction',
      ],
      recommendedActions: [
        'Attempt phone contact',
        'Check with neighbors',
        'Send caregiver for wellness check',
      ],
      confidence: 72,
    },
    status: 'monitoring',
  },
];

// AI Insights Mock Data
export const mockAIInsights: AIInsight[] = [
  {
    id: 'insight-001',
    type: 'savings',
    title: 'Increase Emergency Fund Target',
    description: 'Based on your location\'s high earthquake risk, we recommend increasing your emergency fund to cover 6 months of expenses ($30,000).',
    priority: 'high',
    actionable: true,
    actions: [
      {
        id: 'action-001',
        label: 'Adjust Savings Goal',
        type: 'navigate',
        url: '/safevault/savings',
        icon: 'DollarSign',
      },
    ],
    confidence: 87,
    timestamp: new Date(),
    category: 'Financial Preparedness',
    impact: 'high',
  },
  {
    id: 'insight-002',
    type: 'supply',
    title: 'Water Supply Below Recommended',
    description: 'Your current water supply (24 gallons) is below the recommended 3-day supply for a household of 4 (48 gallons).',
    priority: 'medium',
    actionable: true,
    actions: [
      {
        id: 'action-002',
        label: 'View Recommendations',
        type: 'navigate',
        url: '/safevault/reserves',
        icon: 'Package',
      },
    ],
    confidence: 95,
    timestamp: new Date(),
    category: 'Supply Management',
    impact: 'medium',
  },
  {
    id: 'insight-003',
    type: 'risk',
    title: 'Hurricane Season Approaching',
    description: 'Hurricane season begins in 30 days. Your area has an 85% probability of major hurricane impact. Review evacuation plans.',
    priority: 'critical',
    actionable: true,
    actions: [
      {
        id: 'action-003',
        label: 'View Risk Analysis',
        type: 'navigate',
        url: '/intelligence/climate',
        icon: 'AlertTriangle',
      },
    ],
    confidence: 92,
    timestamp: new Date(),
    expiresAt: new Date(Date.now() + 30 * 24 * 3600000),
    category: 'Climate Risk',
    impact: 'high',
  },
  {
    id: 'insight-004',
    type: 'preparedness',
    title: 'Excellent Progress on Preparedness',
    description: 'Your preparedness score has increased to 78/100. You\'re in the top 15% of users in your region.',
    priority: 'low',
    actionable: false,
    confidence: 100,
    timestamp: new Date(),
    category: 'Achievement',
    impact: 'low',
  },
];

// SafeVault Analytics Mock Data
export const mockSafeVaultAnalytics: SafeVaultAnalytics = {
  userId: 'user-001',
  preparednessScore: mockPreparednessScore,
  savingsSummary: {
    totalSaved: 12500.00,
    monthlyGrowth: 4.2,
    projectedReserve: 25000.00,
    daysOfCoverage: 125,
  },
  supplySummary: {
    totalItems: 8,
    adequateItems: 6,
    lowItems: 1,
    criticalItems: 0,
    expiringItems: 1,
  },
  riskSummary: {
    activeRisks: 4,
    highRisks: 2,
    predictions: 2,
    lastAssessment: new Date(),
  },
  droneSummary: {
    totalDrones: 4,
    availableDrones: 1,
    activeDeliveries: 2,
    completedToday: 7,
  },
  lastUpdated: new Date(),
};

// Export all mock data
export const safeVaultMockData = {
  savings: mockEmergencySavings,
  preparedness: mockPreparednessScore,
  climateRisks: mockClimateRisks,
  reserve: mockEmergencyReserve,
  survivalKits: mockSurvivalKits,
  drones: mockDrones,
  elderlyProfiles: mockElderlyProfiles,
  sosAlerts: mockSOSAlerts,
  inactivityAlerts: mockInactivityAlerts,
  insights: mockAIInsights,
  analytics: mockSafeVaultAnalytics,
};

// Made with Bob